#include "conv_binary_fpga_v2.cpp"
#include "leaky_activate_fpga.cpp"
#include "max_pooling.cpp"
#include "route_layer_fpga.cpp"
#include "shortcut_layer_fpga.cpp"
#include "upsample_x2_fpga.cpp"
#include "yolo_layer_fpga.cpp"
